spring:
  application:
    name: edu-web-management
  #配置数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/edums
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

#MyBatis相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名映射开关
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/*.xml